#!/bin/sh
### BEGIN INIT INFO
# Provides:           redis-server
# Required-Start:     $syslog
# Required-Stop:      $syslog
# Should-Start:       $local_fs
# Should-Stop:        $local_fs
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  redis-server - Persistent key-value db
# Description:        redis-server - Persistent key-value db
### END INIT INFO
 
PATH=/opt/redis/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/bin
DAEMON=`which redis-server`
REDIS_CLI=`which redis-cli`
CONFIG_FILE=/etc/redis.conf
DAEMON_ARGS="$CONFIG_FILE"
NAME=redis-server
DESC=redis-server
PIDFILE=/var/run/redis.pid
LOGFILE=/var/log/redis.log

test -x $DAEMON || exit 0
test -x $DAEMONBOOTSTRAP || exit 0

set -e

case "$1" in
  start)
    if [ -f $PIDFILE ]
    then
      echo -n "$PIDFILE exists, process is already running or crashed\n"
    else
      touch $PIDFILE $LOGFILE
      chown ec2-user:ec2-user $PIDFILE $LOGFILE
      echo -n "Starting Redis server...\n"
      $DAEMON $DAEMON_ARGS
    fi
    ;;    
    
  stop)
    echo "Stopping $DESC"
    if [ ! -e "$PIDFILE" ]
    then
      echo "failed"
    else
      LISTENING_PORT=`grep -E "^ *port +([0-9]+) *$" "$CONFIG_FILE" | grep -Eo "[0-9]+"`
      $REDIS_CLI -p $LISTENING_PORT SHUTDOWN
      while [ -x ${PIDFILE} ]
      do
        echo "Waiting for Redis to shutdown ..."
        sleep 1
      done
      echo "Redis stopped"
      rm -f $PIDFILE
    fi
    ;;

  restart|force-reload)
    ${0} stop
    ${0} start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
